apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubetunnel.fullname" . }}-{{ .Values.env_service_name }}-env
data:
  PORTS: {{ .Values.env_ports }}
  SERVICE_NAME: {{  .Values.env_service_name }}
